export const ROLES = {
  CITIZEN: 'CITIZEN',
  WORKER: 'WORKER',
  INSPECTOR: 'INSPECTOR',
  DEPARTMENT_OFFICER: 'DEPARTMENT_OFFICER',
  WARD_OFFICER: 'WARD_OFFICER',
  MUNICIPAL_ADMIN: 'MUNICIPAL_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

export const ROLE_HIERARCHY = Object.values(ROLES);
