export const MAHARASHTRA_DISTRICTS = [
  "Mumbai City",
  "Mumbai Suburban",
  "Thane",
  "Palghar",
  "Raigad",
  "Ratnagiri",
  "Sindhudurg",
  "Nashik",
  "Dhule",
  "Nandurbar",
  "Jalgaon",
  "Ahilyanagar",
  "Pune",
  "Satara",
  "Sangli",
  "Kolhapur",
  "Solapur",
  "Chhatrapati Sambhajinagar",
  "Jalna",
  "Beed",
  "Dharashiv",
  "Latur",
  "Nanded",
  "Parbhani",
  "Hingoli",
  "Amravati",
  "Akola",
  "Buldhana",
  "Washim",
  "Yavatmal",
  "Nagpur",
  "Wardha",
  "Bhandara",
  "Gondia",
  "Chandrapur",
  "Gadchiroli"
];

export const MAHARASHTRA_DISTRICT_SET = new Set(MAHARASHTRA_DISTRICTS);
